from . import product_brand
from . import micro_remarks
from . import lead_template
from . import sales_template
from . import contacts_template
from . import purchase_template
from . import inventory_template
from . import helpdesk_template
from . import repair_template
from . import doc_footer